//
// EventResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public final class EventResponse: Codable, JSONEncodable, Hashable {

    public var clientId: String?
    public var sourceId: String?
    public var sessionId: String?
    public var date: String?
    public var name: String?
    public var pageName: String?
    public var categoryId: String?
    public var productId: String?
    public var quantity: Double?
    public var price: Double?
    public var container: String?
    public var eventName: String?

    public init(clientId: String? = nil, sourceId: String? = nil, sessionId: String? = nil, date: String? = nil, name: String? = nil, pageName: String? = nil, categoryId: String? = nil, productId: String? = nil, quantity: Double? = nil, price: Double? = nil, container: String? = nil, eventName: String? = nil) {
        self.clientId = clientId
        self.sourceId = sourceId
        self.sessionId = sessionId
        self.date = date
        self.name = name
        self.pageName = pageName
        self.categoryId = categoryId
        self.productId = productId
        self.quantity = quantity
        self.price = price
        self.container = container
        self.eventName = eventName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case clientId = "client_id"
        case sourceId = "source_id"
        case sessionId = "session_id"
        case date
        case name
        case pageName = "page_name"
        case categoryId = "category_id"
        case productId = "product_id"
        case quantity
        case price
        case container
        case eventName = "event_name"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(clientId, forKey: .clientId)
        try container.encodeIfPresent(sourceId, forKey: .sourceId)
        try container.encodeIfPresent(sessionId, forKey: .sessionId)
        try container.encodeIfPresent(date, forKey: .date)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(pageName, forKey: .pageName)
        try container.encodeIfPresent(categoryId, forKey: .categoryId)
        try container.encodeIfPresent(productId, forKey: .productId)
        try container.encodeIfPresent(quantity, forKey: .quantity)
        try container.encodeIfPresent(price, forKey: .price)
        try container.encodeIfPresent(self.container, forKey: .container)
        try container.encodeIfPresent(eventName, forKey: .eventName)
    }

    public static func == (lhs: EventResponse, rhs: EventResponse) -> Bool {
        lhs.clientId == rhs.clientId &&
        lhs.sourceId == rhs.sourceId &&
        lhs.sessionId == rhs.sessionId &&
        lhs.date == rhs.date &&
        lhs.name == rhs.name &&
        lhs.pageName == rhs.pageName &&
        lhs.categoryId == rhs.categoryId &&
        lhs.productId == rhs.productId &&
        lhs.quantity == rhs.quantity &&
        lhs.price == rhs.price &&
        lhs.container == rhs.container &&
        lhs.eventName == rhs.eventName
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(clientId?.hashValue)
        hasher.combine(sourceId?.hashValue)
        hasher.combine(sessionId?.hashValue)
        hasher.combine(date?.hashValue)
        hasher.combine(name?.hashValue)
        hasher.combine(pageName?.hashValue)
        hasher.combine(categoryId?.hashValue)
        hasher.combine(productId?.hashValue)
        hasher.combine(quantity?.hashValue)
        hasher.combine(price?.hashValue)
        hasher.combine(container?.hashValue)
        hasher.combine(eventName?.hashValue)
    }
}
