//
// EventRequestDataAttributes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public final class EventRequestDataAttributes: Codable, JSONEncodable, Hashable {

    public var clientId: String
    public var date: String
    /** Name of a web event. If passed \"user_login\" or \"user_visit\" also writes a session */
    public var name: String
    public var sourceId: String?
    public var sessionId: String?
    public var categoryId: String?
    public var productId: String?
    public var quantity: Double?
    public var price: Double?
    public var container: String?

    public init(clientId: String, date: String, name: String, sourceId: String? = nil, sessionId: String? = nil, categoryId: String? = nil, productId: String? = nil, quantity: Double? = nil, price: Double? = nil, container: String? = nil) {
        self.clientId = clientId
        self.date = date
        self.name = name
        self.sourceId = sourceId
        self.sessionId = sessionId
        self.categoryId = categoryId
        self.productId = productId
        self.quantity = quantity
        self.price = price
        self.container = container
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case clientId = "client_id"
        case date
        case name
        case sourceId = "source_id"
        case sessionId = "session_id"
        case categoryId = "category_id"
        case productId = "product_id"
        case quantity
        case price
        case container
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(clientId, forKey: .clientId)
        try container.encode(date, forKey: .date)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(sourceId, forKey: .sourceId)
        try container.encodeIfPresent(sessionId, forKey: .sessionId)
        try container.encodeIfPresent(categoryId, forKey: .categoryId)
        try container.encodeIfPresent(productId, forKey: .productId)
        try container.encodeIfPresent(quantity, forKey: .quantity)
        try container.encodeIfPresent(price, forKey: .price)
        try container.encodeIfPresent(self.container, forKey: .container)
    }

    public static func == (lhs: EventRequestDataAttributes, rhs: EventRequestDataAttributes) -> Bool {
        lhs.clientId == rhs.clientId &&
        lhs.date == rhs.date &&
        lhs.name == rhs.name &&
        lhs.sourceId == rhs.sourceId &&
        lhs.sessionId == rhs.sessionId &&
        lhs.categoryId == rhs.categoryId &&
        lhs.productId == rhs.productId &&
        lhs.quantity == rhs.quantity &&
        lhs.price == rhs.price &&
        lhs.container == rhs.container
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(clientId.hashValue)
        hasher.combine(date.hashValue)
        hasher.combine(name.hashValue)
        hasher.combine(sourceId?.hashValue)
        hasher.combine(sessionId?.hashValue)
        hasher.combine(categoryId?.hashValue)
        hasher.combine(productId?.hashValue)
        hasher.combine(quantity?.hashValue)
        hasher.combine(price?.hashValue)
        hasher.combine(container?.hashValue)
    }
}
