//
// EventRequestData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public final class EventRequestData: Codable, JSONEncodable, Hashable {

    public var attributes: EventRequestDataAttributes?

    public init(attributes: EventRequestDataAttributes? = nil) {
        self.attributes = attributes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case attributes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(attributes, forKey: .attributes)
    }

    public static func == (lhs: EventRequestData, rhs: EventRequestData) -> Bool {
        lhs.attributes == rhs.attributes
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(attributes?.hashValue)
    }
}
